export {TOP_STORIES_DATA,CURRENT_PAGE_STORY_DATA,
        NEXT_PREV_PAGE_STORY_DATA,
        STORY_DATA_WITH_PAGE_NUMBER,
        STORY_HIDE_STATUS,
        STORY_VOTES,
        LOADING_STATUS,
       } from './HackerNewsConstants';